### ISSUE TITLE
How to assign an alternate function to a key

### ISSUE THREAD

**Issue by jeromegn** [pbludov/hv-kb390l-config#2]
I don't understand the UI with its 3 columns for each key. I imagine there's one for when the Fn key is down, but I can't figure it out.

I'm trying to add media keys after pressing `Fn + <something>`.

Thanks!

**Comment by pbludov** [comment]
> I'm trying to add media keys after pressing `Fn + <something>`.

That's why i've started this project. Unfortunately, the keyboard firmware has no support for such ability.

Each key is encoded by four bytes. The first byte stores the type: key, mouse, macro, usb command. That is, each key can be assigned only one action. I tried to pick different combinations, but no luck.
Please send an email to [havit](https://www.prohavit.com/contact-us/) (I have already sent one), maybe they will add this feature to the firmware.

**Comment by jeromegn** [comment]
I thought their windows drivers allowed this behaviour and it was somehow
possible with this.

I haven’t actually tried the windows drivers, only checked the screenshots.

Thanks for this project btw, it’s pretty neat to at least be able to do
something under Linux :)

So I could bind media keys to keys, just not with a “combination”?

**Comment by pbludov** [comment]
> So I could bind media keys to keys, just not with a “combination”?

Havit has recently updated their driver to version 1.3. Please check it out, but please be careful, it may be dangerous: https://github.com/pbludov/hv-kb390l-config/issues/1

**Comment by jeromegn** [comment]
Oh that seems dangerous.

I didn't realize the assigned shortcuts only worked in game mode. At least I can bind keys I don't use much to media keys and such.

The windows software seems to have support for combination keys according to the manual and videos I've seen. It must be possible to program this. I'm not sure where to begin, is there a way to dump all information going through the USB device? I could try it under windows and see what happens.
